%YAML:1.0
---
camera_matrix: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 1000.9171316987507, 0., 560.7076841584061, 0.,
       1004.5954364689035, 496.53925686933758, 0., 0., 1. ]
dist_coeffs: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [ -0.17818400431764073, 0.082538686865700969,
       0.0019668380097995325, 0.010330165774840061,
       -0.075504837342436237 ]
image_width: 1280
image_height: 1024
