%YAML:1.0
---
rvec: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ 0.017294490378466799, 0.088265178589741464,
       0.0049339312216475214 ]
tvec: !!opencv-matrix
   rows: 3
   cols: 1
   dt: f
   data: [ -17.2486744, -47.695797, 131.356522 ]
R: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 0.99609509878138469, -0.0041645267724566195,
       0.088188496417986303, 0.0056899961406754428, 0.99983838778625478,
       -0.017053511453669422, -0.088103224274840186,
       0.017488711380282847, 0.99595781378863335 ]
